const data = [
    {
        Id: '1',
        name: 'Taichung beauty',
        rating: 5,
        isSpecial: true,
        isNatural: false,
        image: 'https://barritaorchids.com/cdn/shop/products/Cf592_1024x1024.jpg',
        color: 'red',
        numberOfLike: 192,
        origin: 'Taiwan',
        category: 'Cattleya'
    },
    {
        Id: '2',
        name: 'Queen of Thailand',
        rating: 4,
        isSpecial: true,
        isNatural: true,
        image: 'https://thumbs.dreamstime.com/b/orchids-purple-considered-queen-flowers-thailand-71362809.jpg',
        color: 'purple',
        numberOfLike: 245,
        origin: 'Thailand',
        category: 'Cattleya'
    },
    {
        Id: '3',
        name: 'White Moonlight',
        rating: 3,
        isSpecial: false,
        isNatural: true,
        image: 'https://upload.wikimedia.org/wikipedia/commons/5/59/Phalaenopsis_amabilis_Orchi_198.jpg',
        color: 'white',
        numberOfLike: 134,
        origin: 'Vietnam',
        category: 'Phalaenopsis'
    },
    {
        Id: '4',
        name: 'Golden Sunray',
        rating: 4,
        isSpecial: true,
        isNatural: false,
        image: 'https://orchidroots.com/static/utils/images/hybrid/hyb_000031259_100122072.jpg',
        color: 'yellow',
        numberOfLike: 210,
        origin: 'Taiwan',
        category: 'Oncidium'
    },
    {
        Id: '5',
        name: 'Blue Heaven',
        rating: 4,
        isSpecial: false,
        isNatural: false,
        image: 'https://static.vecteezy.com/system/resources/previews/048/240/750/large_2x/blue-orchids-bloom-in-all-their-glory-on-a-sunny-spring-day-view-shows-petals-stamens-leaves-and-buds-on-a-twig-on-a-clear-blue-sky-day-blue-orchid-flower-isolated-on-bright-blue-sky-photo.JPG',
        color: 'blue',
        numberOfLike: 178,
        origin: 'Thailand',
        category: 'Vanda'
    },
    {
        Id: '6',
        name: 'Cattleya Ruby Dream',
        rating: 5,
        isSpecial: true,
        isNatural: false,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJFTT8XcH8vYrQZ_9j_laBy1ID2cA-7B3Wwg&s',
        color: 'purple',
        numberOfLike: 263,
        origin: 'Brazil',
        category: 'Cattleya'
    },
    {
        Id: '7',
        name: 'Phalaenopsis White Angel',
        rating: 4,
        isSpecial: false,
        isNatural: true,
        image: 'https://m.media-amazon.com/images/I/519LN8tsHXL._AC_UF894,1000_QL80_.jpg',
        color: 'white',
        numberOfLike: 189,
        origin: 'Vietnam',
        category: 'Phalaenopsis'
    },
    {
        Id: '8',
        name: 'Dendrobium Stardust Firebird',
        rating: 4,
        isSpecial: true,
        isNatural: true,
        image: 'https://cdn11.bigcommerce.com/s-pxrevx9n0f/images/stencil/1280x1280/products/3747/18655/IMG_0340S__33309.1680813840.JPG?c=2',
        color: 'orange',
        numberOfLike: 211,
        origin: 'Thailand',
        category: 'Dendrobium'
    },
    {
        Id: '9',
        name: 'Vanda Blue Magic',
        rating: 4,
        isSpecial: false,
        isNatural: false,
        image: 'https://i.redd.it/9lox7hj93hx91.jpg',
        color: 'blue',
        numberOfLike: 167,
        origin: 'India',
        category: 'Vanda'
    },
    {
        Id: '10',
        name: 'Oncidium Dancing Lady',
        rating: 3,
        isSpecial: true,
        isNatural: false,
        image: 'https://www.bambooland.com.au/assets/full/ONCJOO.jpg?20210309030920',
        color: 'yellow',
        numberOfLike: 198,
        origin: 'Colombia',
        category: 'Oncidium'
    },
    {
        Id: '11',
        name: 'Cattleya Sunburst',
        rating: 4,
        isSpecial: true,
        isNatural: false,
        image: 'https://cdn11.bigcommerce.com/s-pxrevx9n0f/images/stencil/1280x1280/products/4695/24461/MA-769_Rlc._Yellow_Sunburst_Yuki1__99956.1740529921.jpg?c=2',
        color: 'yellow',
        numberOfLike: 220,
        origin: 'Hawaii',
        category: 'Cattleya',
    },
    {
        Id: '12',
        name: 'Cattleya Pink Doll',
        rating: 4,
        isSpecial: false,
        isNatural: false,
        image: 'https://media.greg.app/Y2FyZS1wbGFudC1wcm9maWxlL3VzZXJzLzI5OTUwNC9wbGFudC1waG90b3MvMTI3MDg2Ny8xNjY4OTk4OTQwNTU2LTY4RjQ4MTdFLTJDM0ItNDg0OC1BRTA2LTUxOEZGQ0I0NTMxMC5wbmc=?auto=webp&width=860&fit=cover&format=pjpg&height=860&optimize=medium&precrop=860:860,smart',
        color: 'pink',
        numberOfLike: 173,
        origin: 'Japan',
        category: 'Cattleya',
    },
    {
        Id: '13',
        name: 'Cattleya Imperial Purple',
        rating: 5,
        isSpecial: true,
        isNatural: false,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYtJ6CP5Fa6n94Qd-ETHKAL9DBZ8doh1EQyw&s',
        color: 'purple',
        numberOfLike: 288,
        origin: 'Brazil',
        category: 'Cattleya',
    },
    {
        Id: '14',
        name: 'Cattleya Lemon Glow',
        rating: 2,
        isSpecial: false,
        isNatural: true,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAvWB2186G0SEF_JmUHKNZd62CBCwNUgmrMQ&s',
        color: 'yellow',
        numberOfLike: 132,
        origin: 'USA',
        category: 'Cattleya',
    },
    {
        Id: '15',
        name: 'Cattleya Fire Kiss',
        rating: 4,
        isSpecial: true,
        isNatural: false,
        image: 'https://static.wixstatic.com/media/356cdc_fd3cbc192b7f4e80aaacbef7c6e81e19~mv2.jpg/v1/fill/w_600,h_600,al_c,q_80,enc_avif,quality_auto/356cdc_fd3cbc192b7f4e80aaacbef7c6e81e19~mv2.jpg',
        color: 'orange',
        numberOfLike: 201,
        origin: 'Ecuador',
        category: 'Cattleya',
    },
    {
        Id: '16',
        name: 'Dendrobium Aphyllum',
        rating: 4,
        isSpecial: true,
        isNatural: true,
        image: 'https://www.nparks.gov.sg/-/media/ffw/protected/flora/6/0/6005/dendrobium_aphyllum_orchidaceae_sbg_swj_20180424_170700_lowres.jpg',
        color: 'pink',
        numberOfLike: 154,
        origin: 'India',
        category: 'Dendrobium'
    }];
export default data;